---
# tasks file for mapr-spark

# Assumes the MapR repos are already configured.

- name: install mapr-spark for RedHat/CentOS
  yum: name='{{item}}' state=present
  with_items:
    - mapr-spark-master
  environment: proxy_env
  when: ansible_distribution in ("CentOS", "RedHat", "Amazon")
  notify:
    - re-run configure.sh to enable spark-master

- name: install mapr-spark for Debian/Ubuntu
  apt: name='{{item}}' state=present
  with_items:
    - mapr-spark-master
  environment: proxy_env
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  notify:
    - re-run configure.sh to enable spark-master

- name: create slaves file
  template: src=slaves.j2 dest={{spark_home}}/conf/slaves mode=0644 owner=root group=root

- name: ensure spark log directory exists
  file: state=directory path=/opt/mapr/spark/spark-{{spark_version}}/logs owner=mapr group=mapr mode=0750
